"""añadir device

Revision ID: 4e739ca5b589
Revises: 6cc89eb49a1b
Create Date: 2026-10-07 18:49:51.672403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e739ca5b589'
down_revision = '6cc89eb49a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amigos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amigos', schema=None) as batch_op:
        batch_op.drop_column('device')

    # ### end Alembic commands ###
